/** Cards & ships — file:// safe mirror of data/collection/*.json */
window.COLLECTION_CONFIG = {
  cards: {
    permanent: [
      { id: 'card_01', num: 1, name: 'Star Magnet I', desc: '+10% magnet pickup radius', effect: { magnetMult: 1.1 } },
      { id: 'card_02', num: 2, name: 'Bargain Cannon', desc: 'Main cannon upgrades cost 10% less', effect: { cannonCostMult: 0.9 } },
      { id: 'card_03', num: 3, name: 'Shield Start', desc: 'Begin each sortie with shield at 100%', effect: { startShieldFull: true } },
      { id: 'card_04', num: 4, name: 'Star Hoarder', desc: '+5% stars banked on stage clear', effect: { starBankMult: 1.05 } },
      { id: 'card_05', num: 5, name: 'Combo Keeper', desc: 'Combo decays 25% slower', effect: { comboDecayMult: 1.25 } },
      { id: 'card_06', num: 6, name: 'Hull Plate', desc: '+8 max shield from hangar baseline', effect: { shieldFlat: 8 } },
      { id: 'card_07', num: 7, name: 'Rapid Loader', desc: '+6% main cannon fire rate', effect: { cannonDpsMult: 1.06 } },
      { id: 'card_08', num: 8, name: 'Rescue Bonus', desc: '+15 score per hostage rescued', effect: { rescueScoreBonus: 15 } },
      { id: 'card_09', num: 9, name: 'Magnet II', desc: '+18% magnet radius', effect: { magnetMult: 1.18 } },
      { id: 'card_10', num: 10, name: 'Elite Hunter', desc: '+12% card/part drop from elites', effect: { lootLuckMult: 1.12 } },
      { id: 'card_11', num: 11, name: 'Bomb Expert', desc: '+1 mega bomb charge if hangar stock > 0', effect: { bonusBombCharge: 1 } },
      { id: 'card_12', num: 12, name: 'Untouchable Pride', desc: '+50★ when earning no-damage medal', effect: { noHitStarBonus: 50 } },
    ],
    temporary: [
      { id: 'temp_double_dmg', name: 'Overdrive', desc: 'Double damage for 15 minutes', durationSec: 900, effect: { damageMult: 2 } },
      { id: 'temp_star_rush', name: 'Star Rush', desc: 'Double run star pickups for 10 minutes', durationSec: 600, effect: { starPickupMult: 2 } },
    ],
  },
  dropRates: {
    eliteCard: 0.08,
    crateCard: 0.12,
    elitePart: 0.06,
    radarPart: 0.05,
    cratePowerup: 0.85,
  },
  ships: {
    enforcer: {
      id: 'enforcer',
      name: 'Enforcer',
      tagline: 'Balanced classic',
      icon: '✈',
      unlockedByDefault: true,
      parts: [],
      mods: { speedMult: 1, shieldMult: 1, luckMult: 1 },
    },
    gladius: {
      id: 'gladius',
      name: 'Gladius',
      tagline: 'Swift striker — less armor',
      icon: '⚡',
      parts: ['gladius_weapon', 'gladius_wing', 'gladius_engine'],
      mods: { speedMult: 1.28, shieldMult: 0.82, luckMult: 1, cannonSpreadTight: true },
    },
    octopus: {
      id: 'octopus',
      name: 'Octopus',
      tagline: 'Swarm missiles instead of wing guns',
      icon: '🐙',
      parts: ['octopus_weapon', 'octopus_wing', 'octopus_engine'],
      mods: { speedMult: 0.95, shieldMult: 1, luckMult: 1, missileSwarm: true },
    },
    ironclad: {
      id: 'ironclad',
      name: 'Iron Clad',
      tagline: 'Heavy hull — slow but tough',
      icon: '🛡',
      parts: ['ironclad_weapon', 'ironclad_wing', 'ironclad_engine'],
      mods: { speedMult: 0.72, shieldMult: 1.45, luckMult: 1, ramDamageMult: 0.6 },
    },
    ace: {
      id: 'ace',
      name: 'Ace of Spades',
      tagline: 'Luck — more cards & parts',
      icon: '♠',
      parts: ['ace_weapon', 'ace_wing', 'ace_engine'],
      mods: { speedMult: 1, shieldMult: 0.95, luckMult: 1.35 },
    },
  },
  partLabels: {
    gladius_weapon: 'Gladius Blaster',
    gladius_wing: 'Gladius Stabilizer',
    gladius_engine: 'Gladius Thruster',
    octopus_weapon: 'Octopus Pod',
    octopus_wing: 'Octopus Tentacle Array',
    octopus_engine: 'Octopus Core',
    ironclad_weapon: 'Iron Cannon',
    ironclad_wing: 'Iron Plate',
    ironclad_engine: 'Iron Drive',
    ace_weapon: 'Ace Barrel',
    ace_wing: 'Ace Fin',
    ace_engine: 'Ace Reactor',
  },
};
