/** Hangar economy — mirrored from data/economy/hangar.json (file:// safe). */
window.HANGAR_CONFIG = {
  version: 3,
  profile: 'moderate-grind',
  modules: {
    hp: {
      label: 'Health (Armor)',
      desc: 'Maximum shield capacity — survive more hits.',
      icon: '🛡',
      unlock: 0,
      base: 35,
      growth: 1.38,
      maxLevel: 10,
    },
    cannon: {
      label: 'Main Cannon',
      desc: 'Primary blaster — faster fire rate and damage.',
      icon: '🔫',
      unlock: 0,
      base: 70,
      growth: 1.42,
      maxLevel: 10,
    },
    wings: {
      label: 'Wing Cannons',
      desc: 'Side shots parallel to your main cannon.',
      icon: '✦',
      unlock: 2500,
      base: 110,
      growth: 1.48,
      maxLevel: 10,
    },
    missiles: {
      label: 'Following Missiles',
      desc: 'Heat-seeking salvos that track enemies below you.',
      icon: '🎯',
      unlock: 2500,
      base: 120,
      growth: 1.48,
      maxLevel: 8,
    },
    magnet: {
      label: 'Star Magnet',
      desc: 'Vacuum radius for star pickups.',
      icon: '🧲',
      unlock: 800,
      base: 55,
      growth: 1.44,
      maxLevel: 10,
    },
    laser: {
      label: 'Laser (Stock)',
      desc: 'Screen-melting beam — single-use charges per sortie.',
      icon: '⚡',
      unlock: 2500,
      base: 120,
      growth: 1.48,
      maxLevel: 6,
    },
    energy_shield: {
      label: 'Energy Shield (Stock)',
      desc: 'Temporary invincibility bubble — per-sortie charges.',
      icon: '🔮',
      unlock: 2500,
      base: 115,
      growth: 1.48,
      maxLevel: 6,
    },
    mega_bomb: {
      label: 'Mega Bomb (Stock)',
      desc: 'Clears bullets and damages all enemies — per-sortie charges.',
      icon: '💥',
      unlock: 2500,
      base: 115,
      growth: 1.48,
      maxLevel: 6,
    },
  },
  difficulty: {
    order: ['normal', 'hard', 'insane', 'nightmare'],
    labels: { normal: 'Normal', hard: 'Hard', insane: 'Insane', nightmare: 'Nightmare' },
    enemyHp: { normal: 1, hard: 1.25, insane: 1.5, nightmare: 1.85 },
    bulletSpeed: { normal: 1, hard: 1.12, insane: 1.28, nightmare: 1.45 },
    starMult: { normal: 1, hard: 1.3, insane: 1.55, nightmare: 1.75 },
  },
  medals: [
    { id: 'destroy70', label: '70% Annihilation', short: '70%' },
    { id: 'destroy100', label: '100% Annihilation', short: '100%' },
    { id: 'rescueAll', label: 'Rescue All', short: 'Rescue' },
    { id: 'noHit', label: 'Untouched', short: 'Perfect' },
  ],
  stagePayout: { clearBase: 125, clearPerStage: 40, medalBonus: 100, rescueBonus: 50 },
};
