/** Stage 4 — Black Coast (mirrors data/stages/stage-04.json). */
window.SKY_FORCE_STAGES = window.SKY_FORCE_STAGES || {};
window.SKY_FORCE_STAGES['stage-04'] = {
  id: 4,
  name: 'Black Coast',
  subtitle: 'Sector 24 — Naval battery line',
  theme: 'fleet',
  hostageCount: 3,
  unlockStars: 0,
  difficultyMultipliers: {
    normal: { enemyHp: 1.38, bulletSpeed: 1.12, starReward: 1.2 },
  },
  timeline: [
    { atSec: 0, action: 'banner', text: 'SECTOR 24 — BLACK COAST', kind: 'stage' },
    { atSec: 0, action: 'setSection', section: 1 },
    { atSec: 4, action: 'banner', text: 'SHORE CANNONS', kind: 'wave' },
    { atSec: 5, action: 'spawnGroup', enemies: [
      { type: 'turret', x: 0.12, y: 0.7 },
      { type: 'turret', x: 0.88, y: 0.7 },
      { type: 'turret', x: 0.5, y: 0.73 },
      { type: 'tank', x: 0.35, y: 0.76 },
    ] },
    { atSec: 10, action: 'spawnDestructible', destructible: 'radar', x: 0.22, y: 0.78 },
    { atSec: 12, action: 'spawnDestructible', destructible: 'radar', x: 0.78, y: 0.77 },
    { atSec: 16, action: 'spawnHostage', id: 'h1', x: 0.3, y: 0.59 },
    { atSec: 20, action: 'spawnGroup', enemies: [
      { type: 'tank', x: 0.2, y: 0.72 },
      { type: 'tank', x: 0.8, y: 0.72 },
      { type: 'turret', x: 0.5, y: 0.75 },
    ] },
    { atSec: 26, action: 'setSection', section: 2 },
    { atSec: 26, action: 'banner', text: 'ARTILLERY ROW', kind: 'wave' },
    { atSec: 28, action: 'spawnGroup', enemies: [
      { type: 'turret', x: 0.25, y: 0.68 },
      { type: 'turret', x: 0.5, y: 0.7 },
      { type: 'turret', x: 0.75, y: 0.68 },
      { type: 'tank', x: 0.5, y: 0.77, elite: true },
    ] },
    { atSec: 34, action: 'spawnDestructible', destructible: 'crate', x: 0.15, y: 0.74 },
    { atSec: 36, action: 'spawnDestructible', destructible: 'crate', x: 0.85, y: 0.73 },
    { atSec: 38, action: 'spawnHostage', id: 'h2', x: 0.68, y: 0.58 },
    { atSec: 42, action: 'spawnGroup', enemies: [
      { type: 'tank', x: 0.32, y: 0.73 },
      { type: 'tank', x: 0.68, y: 0.73 },
      { type: 'turret', x: 0.18, y: 0.76 },
      { type: 'turret', x: 0.82, y: 0.76 },
    ] },
    { atSec: 48, action: 'setSection', section: 3 },
    { atSec: 48, action: 'banner', text: 'COASTAL SIEGE', kind: 'wave' },
    { atSec: 50, action: 'spawnHostage', id: 'h3', x: 0.5, y: 0.56 },
    { atSec: 52, action: 'spawnGroup', enemies: [
      { type: 'tank', x: 0.25, y: 0.74 },
      { type: 'tank', x: 0.75, y: 0.74 },
      { type: 'tank', x: 0.4, y: 0.77, elite: true },
      { type: 'tank', x: 0.6, y: 0.77 },
      { type: 'turret', x: 0.5, y: 0.68 },
    ] },
    { atSec: 58, action: 'spawnDestructible', destructible: 'fuel', x: 0.3, y: 0.79 },
    { atSec: 60, action: 'spawnDestructible', destructible: 'fuel', x: 0.7, y: 0.78 },
    { atSec: 64, action: 'spawnGroup', enemies: [
      { type: 'turret', x: 0.35, y: 0.71 },
      { type: 'turret', x: 0.65, y: 0.71 },
      { type: 'tank', x: 0.5, y: 0.76, elite: true },
    ] },
    { atSec: 68, action: 'setSection', section: 4 },
    { atSec: 68, action: 'banner', text: 'SIEGE PLATFORM', kind: 'boss' },
    { atSec: 72, action: 'spawnBoss', type: 'dreadnought', hp: 6400, name: 'SIEGE PLATFORM', radius: 46, fireScale: 1.1 },
  ],
  medals: {
    annihilation70: { threshold: 0.7 },
    annihilation100: { threshold: 1 },
    rescueAll: { survivorIds: [] },
  },
  clearBonusStars: 110,
};
